// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto_defs/proto_defs.proto

package proto_defs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssetService_RegisterAsset_FullMethodName    = "/AssetService/RegisterAsset"
	AssetService_SendOrder_FullMethodName        = "/AssetService/SendOrder"
	AssetService_SendResponse_FullMethodName     = "/AssetService/SendResponse"
	AssetService_CheckIn_FullMethodName          = "/AssetService/CheckIn"
	AssetService_CheckSession_FullMethodName     = "/AssetService/CheckSession"
	AssetService_GetHistory_FullMethodName       = "/AssetService/GetHistory"
	AssetService_Subscribe_FullMethodName        = "/AssetService/Subscribe"
	AssetService_StartNewListener_FullMethodName = "/AssetService/StartNewListener"
)

// AssetServiceClient is the client API for AssetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type AssetServiceClient interface {
	// Register asset (ServerSide)
	RegisterAsset(ctx context.Context, in *AssetRegistration, opts ...grpc.CallOption) (*RegistrationConfirmation, error)
	// Send order from server and get asset response (ServerSide)
	SendOrder(ctx context.Context, in *ServerOrder, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Send response after asset registration (ClientSide)
	SendResponse(ctx context.Context, in *AssetResponse, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CheckIn(ctx context.Context, in *AssetResponse, opts ...grpc.CallOption) (*ServerOrder, error)
	CheckSession(ctx context.Context, in *None, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Session], error)
	GetHistory(ctx context.Context, in *HistoryQuery, opts ...grpc.CallOption) (*HistoryQuery, error)
	Subscribe(ctx context.Context, in *Notification, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notification], error)
	StartNewListener(ctx context.Context, in *Listener, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type assetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetServiceClient(cc grpc.ClientConnInterface) AssetServiceClient {
	return &assetServiceClient{cc}
}

func (c *assetServiceClient) RegisterAsset(ctx context.Context, in *AssetRegistration, opts ...grpc.CallOption) (*RegistrationConfirmation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationConfirmation)
	err := c.cc.Invoke(ctx, AssetService_RegisterAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) SendOrder(ctx context.Context, in *ServerOrder, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AssetService_SendOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) SendResponse(ctx context.Context, in *AssetResponse, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AssetService_SendResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) CheckIn(ctx context.Context, in *AssetResponse, opts ...grpc.CallOption) (*ServerOrder, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerOrder)
	err := c.cc.Invoke(ctx, AssetService_CheckIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) CheckSession(ctx context.Context, in *None, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Session], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AssetService_ServiceDesc.Streams[0], AssetService_CheckSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[None, Session]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AssetService_CheckSessionClient = grpc.ServerStreamingClient[Session]

func (c *assetServiceClient) GetHistory(ctx context.Context, in *HistoryQuery, opts ...grpc.CallOption) (*HistoryQuery, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryQuery)
	err := c.cc.Invoke(ctx, AssetService_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) Subscribe(ctx context.Context, in *Notification, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AssetService_ServiceDesc.Streams[1], AssetService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Notification, Notification]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AssetService_SubscribeClient = grpc.ServerStreamingClient[Notification]

func (c *assetServiceClient) StartNewListener(ctx context.Context, in *Listener, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AssetService_StartNewListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetServiceServer is the server API for AssetService service.
// All implementations must embed UnimplementedAssetServiceServer
// for forward compatibility.
//
// Service definition
type AssetServiceServer interface {
	// Register asset (ServerSide)
	RegisterAsset(context.Context, *AssetRegistration) (*RegistrationConfirmation, error)
	// Send order from server and get asset response (ServerSide)
	SendOrder(context.Context, *ServerOrder) (*emptypb.Empty, error)
	// Send response after asset registration (ClientSide)
	SendResponse(context.Context, *AssetResponse) (*emptypb.Empty, error)
	CheckIn(context.Context, *AssetResponse) (*ServerOrder, error)
	CheckSession(*None, grpc.ServerStreamingServer[Session]) error
	GetHistory(context.Context, *HistoryQuery) (*HistoryQuery, error)
	Subscribe(*Notification, grpc.ServerStreamingServer[Notification]) error
	StartNewListener(context.Context, *Listener) (*emptypb.Empty, error)
	mustEmbedUnimplementedAssetServiceServer()
}

// UnimplementedAssetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetServiceServer struct{}

func (UnimplementedAssetServiceServer) RegisterAsset(context.Context, *AssetRegistration) (*RegistrationConfirmation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAsset not implemented")
}
func (UnimplementedAssetServiceServer) SendOrder(context.Context, *ServerOrder) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOrder not implemented")
}
func (UnimplementedAssetServiceServer) SendResponse(context.Context, *AssetResponse) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendResponse not implemented")
}
func (UnimplementedAssetServiceServer) CheckIn(context.Context, *AssetResponse) (*ServerOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIn not implemented")
}
func (UnimplementedAssetServiceServer) CheckSession(*None, grpc.ServerStreamingServer[Session]) error {
	return status.Errorf(codes.Unimplemented, "method CheckSession not implemented")
}
func (UnimplementedAssetServiceServer) GetHistory(context.Context, *HistoryQuery) (*HistoryQuery, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedAssetServiceServer) Subscribe(*Notification, grpc.ServerStreamingServer[Notification]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedAssetServiceServer) StartNewListener(context.Context, *Listener) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartNewListener not implemented")
}
func (UnimplementedAssetServiceServer) mustEmbedUnimplementedAssetServiceServer() {}
func (UnimplementedAssetServiceServer) testEmbeddedByValue()                      {}

// UnsafeAssetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetServiceServer will
// result in compilation errors.
type UnsafeAssetServiceServer interface {
	mustEmbedUnimplementedAssetServiceServer()
}

func RegisterAssetServiceServer(s grpc.ServiceRegistrar, srv AssetServiceServer) {
	// If the following call pancis, it indicates UnimplementedAssetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssetService_ServiceDesc, srv)
}

func _AssetService_RegisterAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetRegistration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).RegisterAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_RegisterAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).RegisterAsset(ctx, req.(*AssetRegistration))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_SendOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).SendOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_SendOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).SendOrder(ctx, req.(*ServerOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_SendResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).SendResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_SendResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).SendResponse(ctx, req.(*AssetResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_CheckIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).CheckIn(ctx, req.(*AssetResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_CheckSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(None)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AssetServiceServer).CheckSession(m, &grpc.GenericServerStream[None, Session]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AssetService_CheckSessionServer = grpc.ServerStreamingServer[Session]

func _AssetService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetHistory(ctx, req.(*HistoryQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Notification)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AssetServiceServer).Subscribe(m, &grpc.GenericServerStream[Notification, Notification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AssetService_SubscribeServer = grpc.ServerStreamingServer[Notification]

func _AssetService_StartNewListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Listener)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).StartNewListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_StartNewListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).StartNewListener(ctx, req.(*Listener))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetService_ServiceDesc is the grpc.ServiceDesc for AssetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AssetService",
	HandlerType: (*AssetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAsset",
			Handler:    _AssetService_RegisterAsset_Handler,
		},
		{
			MethodName: "SendOrder",
			Handler:    _AssetService_SendOrder_Handler,
		},
		{
			MethodName: "SendResponse",
			Handler:    _AssetService_SendResponse_Handler,
		},
		{
			MethodName: "CheckIn",
			Handler:    _AssetService_CheckIn_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _AssetService_GetHistory_Handler,
		},
		{
			MethodName: "StartNewListener",
			Handler:    _AssetService_StartNewListener_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CheckSession",
			Handler:       _AssetService_CheckSession_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _AssetService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto_defs/proto_defs.proto",
}
